import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {cidOf,cidMatches,keyId,verifyObject,decodeCid,jcs,encodeFrame,decodeFrames,deterministicTestKey,signObject} from '../reference/codec.mjs';
const E=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../examples');
const read=n=>JSON.parse(fs.readFileSync(path.join(E,n+'.json')));
function assert(x,msg){if(!x)throw Error(msg);}
const A=read('authority-descriptor'), C=read('certificate'), P=read('post'), R=read('reply'),N=read('node-a'),B=read('node-b'),REV=read('revocations'),IDs=read('identifiers');
const aKey=A.payload.public_key,uKey=C.payload.subject_key,nKey=N.payload.node_key,bKey=B.payload.node_key;
for(const [obj,k,domain] of [[A,aKey,'authority'],[C,aKey,'certificate'],[P,uKey,'post'],[R,uKey,'post'],[N,nKey,'node'],[B,bKey,'node'],[REV,aKey,'revocations']]) assert(verifyObject(obj,k,domain),'signature '+domain);
assert(P.payload.certificate_cid===cidOf(C),'referência ao certificado');
assert(P.payload.author_key_id===keyId(uKey),'vínculo do autor');
assert(C.payload.issuer_id===keyId(aKey),'vínculo da AC');
const authorityTestKey=deterministicTestKey('authority-axipy');
assert(authorityTestKey.id===C.payload.issuer_id,'chave de teste da AC');
const alternateCert=signObject({...C.payload,policy_id:'alternate-test-policy'},authorityTestKey.privatePem,'certificate');
assert(verifyObject(alternateCert,aKey,'certificate'),'certificado alternativo assinado pela mesma AC');
assert(alternateCert.payload.subject_key.x===uKey.x,'certificado alternativo da mesma chave');
assert(cidOf(alternateCert)!==P.payload.certificate_cid,'troca de certificado muda CID');
const swappedPost={...P,payload:{...P.payload,certificate_cid:cidOf(alternateCert)}};
assert(!verifyObject(swappedPost,uKey,'post'),'alteração do CID no post invalida assinatura');
const userTestKey=deterministicTestKey('user-ana');
assert(userTestKey.id===P.payload.author_key_id,'chave de teste do autor');
const composed=signObject({...P.payload,text:'é'},userTestKey.privatePem,'post');
const decomposed=signObject({...P.payload,text:'e\u0301'},userTestKey.privatePem,'post');
assert(verifyObject(composed,uKey,'post') && verifyObject(decomposed,uKey,'post'),'formas Unicode assinadas');
assert(cidOf(composed)!==cidOf(decomposed),'Unicode não é normalizado antes do CID');
assert(R.payload.reply_to===cidOf(P),'referência ao post pai');
assert(cidOf(C)===IDs.cids.certificate && cidOf(P)===IDs.cids.post,'CID vs Python');
assert(decodeCid(cidOf(P)).length===32,'digest do CID');
const bad=read('post-tampered-INVALID');
assert(!verifyObject(bad,uKey,'post') && !cidMatches(cidOf(P),bad),'post adulterado');
const unk=read('certificate-untrusted');
assert(unk.payload.issuer_id!==C.payload.issuer_id,'autoridade fora do conjunto local');
for(const f of fs.readdirSync(E).filter(n=>n.startsWith('wire-')&&n.endsWith('.json'))){
 const obj=JSON.parse(fs.readFileSync(path.join(E,f)));
 const k=obj.payload.from===N.payload.node_id?nKey:bKey;
 assert(verifyObject(obj,k,'wire'),'wire signature '+f);
 const framed=encodeFrame(obj);
 const a=decodeFrames(framed.subarray(0,2)); assert(a.messages.length===0 && a.remainder.length===2,'prefixo fragmentado');
 const b=decodeFrames(Buffer.concat([a.remainder,framed.subarray(2)]));
 assert(b.messages.length===1 && b.remainder.length===0,'recomposição TCP');
 assert(jcs(b.messages[0]).equals(jcs(obj)),'frame roundtrip');
}
const hello=read('wire-hello').payload,challenge=read('wire-challenge').payload;
const confirm=read('wire-confirm').payload,ready=read('wire-ready').payload;
assert([challenge,confirm,ready].every(m=>m.request_id===hello.request_id),'correlação do handshake');
assert(hello.session_id===null && challenge.session_id===null,'sessão ainda não estabelecida');
assert(challenge.body.nonce_a===hello.body.nonce_a && confirm.body.nonce_a===hello.body.nonce_a,'eco nonce_a');
assert(confirm.body.nonce_b===challenge.body.nonce_b,'eco nonce_b');
assert([confirm,ready].every(m=>m.session_id===challenge.body.session && m.body.session===challenge.body.session),'ID de sessão do handshake');
assert(jcs(Object.keys(hello.body).sort()).equals(jcs(['node_key','nonce_a','wire_versions'].sort())),'HELLO sem lista de ACs');
assert(jcs(Object.keys(challenge.body).sort()).equals(jcs(['node_key','nonce_a','nonce_b','session'].sort())),'CHALLENGE sem lista de ACs');
assert(jcs(Object.keys(ready.body)).equals(jcs(['session'])),'READY sem lista de ACs');
assert(hello.body.wire_versions.includes('2') && hello.from===keyId(hello.body.node_key),'versão e identidade de A');
assert(challenge.from===keyId(challenge.body.node_key),'identidade de B');
const tamperedChallenge=read('wire-challenge');
tamperedChallenge.payload.body.nonce_a=confirm.body.nonce_b;
assert(!verifyObject(tamperedChallenge,bKey,'wire'),'nonce adulterado invalida assinatura');
const announce=read('wire-announce').payload.body;
assert(announce.cid===cidOf(P) && announce.issuer_id===C.payload.issuer_id && announce.author_key_id===P.payload.author_key_id,'anúncio coerente com post e certificado');
assert(announce.issuer_id!==unk.payload.issuer_id,'autoridade anunciada não equivale a qualquer certificado');
const issue=read('issue-result'),sub=read('issue-submit');
assert(verifyObject(issue,aKey,'issue_result'),'resultado emitido pela autoridade');
assert(verifyObject(sub.forward,nKey,'forward'),'encaminhamento assinado');
assert(sub.forward.payload.request_cid===cidOf(sub.request),'encaminhamento ligado ao pedido');
assert(jcs(P).length<262144,'bloco dentro dos limites');
assert(Buffer.byteLength(P.payload.text,'utf8')<=16384,'text dentro do limite');
console.log('PASS: Node Ed25519, CIDv1 raw, autor/certificado, mensagem Wire e cadastro');
console.log('PASS: frames TCP fragmentados, conteúdo adulterado rejeitado, AC distinta identificada');
console.log('PASS: certificado alternativo da mesma chave não substitui certificate_cid assinado');
console.log('PASS: formas Unicode visualmente similares mantêm CIDs distintos');
console.log('PASS: fixtures de handshake, sessão e anúncio coerentes');
